<a href="https://colab.research.google.com/github/phionex2/Deep-Learning/blob/main/supervised_word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [3]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restaurant",30)

[10, 2]

In [5]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[9, 27], [10, 2], [7, 8], [26, 9, 18], [23, 26, 25], [9, 27], [19, 26, 26], [7, 18], [7, 17], [12, 23]]


In [6]:

max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 9 27  0  0]
 [10  2  0  0]
 [ 7  8  0  0]
 [26  9 18  0]
 [23 26 25  0]
 [ 9 27  0  0]
 [19 26 26  0]
 [ 7 18  0  0]
 [ 7 17  0  0]
 [12 23  0  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:

X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171 (684.00 Byte)
Trainable params: 171 (684.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 141ms/step - loss: 0.6385 - accuracy: 0.8000


0.800000011920929

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]

array([ 0.0148429 , -0.03247032, -0.01778231, -0.04112619, -0.04123257],
      dtype=float32)

In [14]:
weights[16]

array([ 0.01400418, -0.02672787, -0.02522975, -0.04513536,  0.00888002],
      dtype=float32)